### ISSUE TITLE
Prod todo list

### ISSUE THREAD

**Issue by PierrickP** [parisjs/parisjs-website#135]
+ [x] Create Github app 
+ [x] Hellojs setting
+ [x] Set travis for phenomic build
+ [x] Setup https only

**Comment by fazouane-marouane** [comment]
I'd add "support for https"/"https only site" to the list, since we'll be carrying around access tokens to GitHub (in the callback from hellojs for instance).
We can maybe use netlify for this? I already used it once, and it's extremely easy to setup.

**Comment by fazouane-marouane** [comment]
I deployed my fork of refonte2018 on netlify. Everything works great
https://parisjs-fork-marouane.netlify.com

**Comment by molokoloco** [comment]
Ca avance bien, bravo à tous 👍👌

🌮

Le 6 janv. 2018 7:26 PM, "Marouane Fazouane" <notifications@github.com> a
écrit :

**Comment by DjebbZ** [comment]
Super, il reste plus grand chose ! La page sponsors n'a pas encore de
contenus c'est ça ?

Franchement Big up à vous, joli taff !
